DROP DATABASE IF EXISTS brewery;
DROP USER IF EXISTS `brewery_service`@`%`;
CREATE DATABASE IF NOT EXISTS brewery CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE USER IF NOT EXISTS `brewery_service`@`%` IDENTIFIED WITH mysql_native_password BY 'password';
GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, REFERENCES, INDEX, ALTER, EXECUTE, CREATE VIEW, SHOW VIEW,
    CREATE ROUTINE, ALTER ROUTINE, EVENT, TRIGGER ON `brewery`.* TO `brewery_service`@`%`;